---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /
  
- search:
    provider: [brave, google, duckduckgo]
    target: _blank
    focus: true
    showSearchSuggestions: true
    
- openweathermap:
    label: home #optional
    latitude: 12.3456789
    longitude: 12.3456789
    units: imperial
    provider: openweathermap
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1
